src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 25)]
    private ?string $pseudo = null;

    #[ORM\Column(length: 255)]
    private ?string $location = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $photo = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Demand::class, orphanRemoval: true)]
    protected Collection $demands;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: DemandRelation::class)]
    private Collection $demandRelations;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Message::class)]
    private Collection $messages;

    #[ORM\OneToMany(mappedBy: 'user_liker', targetEntity: Like::class)]
    private Collection $likers;

    #[ORM\OneToMany(mappedBy: 'user_liked', targetEntity: Like::class)]
    private Collection $likeds;

    public function __construct()
    {
        $this->demands = new ArrayCollection();
        $this->demandRelations = new ArrayCollection();
        $this->messages = new ArrayCollection();
        $this->likers = new ArrayCollection();
        $this->likeds = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * @return Collection<int, Demand>
     */
    public function getDemands(): Collection
    {
        return $this->demands;
    }

    public function addDemand(Demand $demand): self
    {
        if (!$this->demands->contains($demand)) {
            $this->demands->add($demand);
            $demand->setUser($this);
        }

        return $this;
    }

    public function removeDemand(Demand $demand): self
    {
        if ($this->demands->removeElement($demand)) {
            // set the owning side to null (unless already changed)
            if ($demand->getUser() === $this) {
                $demand->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, DemandRelation>
     */
    public function getDemandRelations(): Collection
    {
        return $this->demandRelations;
    }

    public function addDemandRelation(DemandRelation $demandRelation): self
    {
        if (!$this->demandRelations->contains($demandRelation)) {
            $this->demandRelations->add($demandRelation);
            $demandRelation->setUser($this);
        }

        return $this;
    }

    public function removeDemandRelation(DemandRelation $demandRelation): self
    {
        if ($this->demandRelations->removeElement($demandRelation)) {
            // set the owning side to null (unless already changed)
            if ($demandRelation->getUser() === $this) {
                $demandRelation->setUser(null);
            }
        }

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
    
    public function __toString(){
    return $this->id;
    }

    /**
     * @return Collection<int, Message>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages->add($message);
            $message->setUser($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getUser() === $this) {
                $message->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Like>
     */
    public function getLikers(): Collection
    {
        return $this->likers;
    }

    public function addLiker(Like $liker): self
    {
        if (!$this->likers->contains($liker)) {
            $this->likers->add($liker);
            $liker->setUserLiker($this);
        }

        return $this;
    }

    public function removeLiker(Like $liker): self
    {
        if ($this->likers->removeElement($liker)) {
            // set the owning side to null (unless already changed)
            if ($liker->getUserLiker() === $this) {
                $liker->setUserLiker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Like>
     */
    public function getLikeds(): Collection {
        return $this->likeds;
    }

    public function addLiked(Like $liked): self
    {
        if (!$this->likeds->contains($liked)) {
            $this->likeds->add($liked);
            $liked->setUserLiked($this);
        }

        return $this;
    }

    public function removeLiked(Like $liked): self
    {
        if ($this->likeds->removeElement($liked)) {
            // set the owning side to null (unless already changed)
            if ($liked->getUserLiked() === $this) {
                $liked->setUserLiked(null);
            }
        }

        return $this;
    }

    public function isLikedByUser(User $user): bool {
        $userLikeds = $this->getLikeds();
        if($userLikeds != null ){
            foreach($userLikeds as $userLiked){
               
                if($userLiked->getUserLiker() == $user){  
                    return true;
                }
            }
        }
        return false;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    #[Route(path: '/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        
        if ($this->getUser()) { 
            return $this->redirectToRoute('app_demand_index', [], Response::HTTP_SEE_OTHER);
        }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    #[Route(path: '/logout', name: 'app_logout')]
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}



{% block body %}
    <header class="pt-5 pb-5 d-flex flex-wrap flex-column">
            <h1 class="text-center p-5" >Connectez vous pour profiter de la communauté Help and Share</h1>     
    </header>

    {% for message in app.flashes('success') %}
        <div class="flash-notice alert alert-success">
            {{ message }}
        </div>
    {% endfor %}

    <div class="container p-5">
        <div class="row justify-content-center">
            <div class="col-10" style="min-width: 200px; max-width: 400px;">

                <form class="form-signin" method="post">
                    {% if error %}
                        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
                    {% endif %}

                    {% if app.user %}
                        <div class="mb-3">
                            You are logged in as {{ app.user.userIdentifier }}, <a href="{{ path('app_logout') }}">Logout</a>
                        </div>
                    {% endif %}

                    <label for="inputEmail">Email</label>
                    <input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control mb-3" autocomplete="email" required autofocus>
                    <label for="inputPassword">Password</label>
                    <input type="password" name="password" id="inputPassword" class="form-control mb-3 " autocomplete="current-password" required>

                    <input type="hidden" name="_csrf_token"
                        value="{{ csrf_token('authenticate') }}"
                    >

                        {#     
                        Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
                        See https://symfony.com/doc/current/security/remember_me.html #}

                        {# <div class="checkbox mb-3">
                            <label>
                                <input type="checkbox" name="_remember_me"> Remember me
                            </label>
                        </div> #}
                

                    <button class="btn btn-lg btn-primary mt-3 mb-3" type="submit">
                        Sign in
                    </button>
                </form>
                <a  href="{{ path('app_register') }}">S'inscrire</a>

            </div>
        </div>
    </div>

{% endblock %}