src/Entity/Demand.php
<?php

namespace App\Entity;

use App\Repository\DemandRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: DemandRepository::class)]
class Demand
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;


    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank]
    #[Assert\NotNull]
    #[Assert\Length(
        min: 10,
        max: 50,
        minMessage: 'Votre titre doit faire minimum {{ limit }} caractères',
        maxMessage: 'Votre titre doit faire maximum {{ limit }} caractères',
    )]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank]
    #[Assert\NotNull]
    #[Assert\Length(
        min: 10,
        max: 200,
        minMessage: 'Votre message doit faire minimum {{ limit }} caractères',
        maxMessage: 'Votre message doit faire maximum {{ limit }} caractères',
    )]
    private ?string $text = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $photo = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_created = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_modified = null;
    
    #[ORM\Column]
    private ?bool $deleted = null;

    #[ORM\ManyToOne(inversedBy: 'demands')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'demand', targetEntity: DemandRelation::class)]
    private Collection $demandRelations;

    public function __construct()
    {
        $this->demandRelations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->date_created;
    }

    public function setDateCreated(\DateTimeInterface $date_created): self
    {
        $this->date_created = $date_created;

        return $this;
    }

    public function getDateModified(): ?\DateTimeInterface
    {
        return $this->date_modified;
    }

    public function setDateModified(\DateTimeInterface $date_modified): self
    {
        $this->date_modified = $date_modified;

        return $this;
    }

    public function isDeleted(): ?bool
    {
        return $this->deleted;
    }

    public function setDeleted(bool $deleted): self
    {
        $this->deleted = $deleted;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function __toString(){
    return $this->id;
    }
    /**
     * @return Collection<int, DemandRelation>
     */
    public function getDemandRelations(): Collection
    {
        return $this->demandRelations;
    }

    public function addDemandRelation(DemandRelation $demandRelation): self
    {
        if (!$this->demandRelations->contains($demandRelation)) {
            $this->demandRelations->add($demandRelation);
            $demandRelation->setDemand($this);
        }

        return $this;
    }

    public function removeDemandRelation(DemandRelation $demandRelation): self
    {
        if ($this->demandRelations->removeElement($demandRelation)) {
            // set the owning side to null (unless already changed)
            if ($demandRelation->getDemand() === $this) {
                $demandRelation->setDemand(null);
            }
        }

        return $this;
    }

    // If the connected user has already responded to the demand or if he is the one who got a response to his demand
    public function isRelated(User $user): bool {
        
        // Get all relations of this demand
        $relations = $this->getDemandRelations();

        // If there is at least 1 relation on this demand
        if($relations != null ){
            foreach($relations as $relation){

                // If the connected user has already responded to the demand or if he is the one who got a response to his demand
                if($relation->getUser() == $user or $relation->getDemand()->getUser() == $user){
                    return true;
                }
            }
        }
        return false;
    }
}

src/Form/DemandType.php
<?php

namespace App\Form;

use App\Entity\Demand;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class DemandType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title' , TextType::class, [
                'label' => 'Titre',
                'attr' => [
                    'placeholder' => 'Titre',
                    'maxlength' => "50",
                    'minlength' => "10",
                ],
                'row_attr' => [
                    'class' => 'form-floating mb-3',
                ],
            ])
            ->add('text' , TextareaType::class, [
                'label' => 'Texte',
                'attr' => [
                    'placeholder' => 'text',
                    'maxlength' => "200",
                ],
                'row_attr' => [
                    'class' => 'form-floating mb-3 h',
                ],
            ])
            ->add('photo', FileType::class, [
                'label' => 'Image',
                
                // make it optional so you don't have to re-upload the photo
                // every time you edit the Demand details
                'required' => false,

                // unmapped means that this field is not associated to any entity property
                'mapped' => false,



                // unmapped fields can't define their validation using annotations
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '5M',
                        'mimeTypes' => [
                            'image/*',
                            'application/pdf',
                            'application/x-pdf',
                        ],
                        'mimeTypesMessage' => 'Veuillez choisir un fichier image valide ( ex: jpeg,png )',
                    ])
                ],
            ])
        ;
    }

    
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Demand::class,
        ]);
    }
}

src/Controller/DemandController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\Demand;
use App\Form\DemandType;
use App\Service\FileUploader;
use App\Repository\DemandRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\DemandRelationRepository;
use App\Repository\LikeRepository;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/')]
class DemandController extends AbstractController
{

    /*______________________________________________________________________________

                                        HOME
     ↓↓↓↓↓↓↓↓↓↓↓↓↓                                                       ↓↓↓↓↓↓↓↓↓↓↓↓                                   
    _________________________________________________________________________________*/
    #[Route('/', name: 'app_demand_index', methods: ['GET','POST'])]
    public function index(Request $request,DemandRepository $demandRepository): Response
    {
        $request = Request::createFromGlobals();
        
        $search = $request->request->get('search');
       
        if ($search) {
            return $this->render('demand/index.html.twig', [
            'demands' => $demandRepository->search($search),
            ]);
        }
        return $this->render('demand/index.html.twig', [
            'demands' => $demandRepository->findAll(),
        ]);
    }


    /*______________________________________________________________________________

                                        MY_DEMANDS
    ↓↓↓↓↓↓↓↓↓↓↓↓↓                                                       ↓↓↓↓↓↓↓↓↓↓↓↓	
    _________________________________________________________________________________*/
    #[Route('/mes_demandes', name: 'my_demands', methods: ['GET'])]
    public function demandUser(DemandRepository $demandRepository): Response
    {
        if ($this->getUser())
        {
        // Get logged user's object
        $user = (object) $this->getUser();
        return $this->render('demand/my_demands.html.twig', [
            'demands' => $demandRepository->findBy(['user'=> $user]),
        ]);
        }
        else
        {
            return $this->redirectToRoute('app_login');
        }
    }


    /*______________________________________________________________________________

                                        NEW
     ↓↓↓↓↓↓↓↓↓↓↓↓↓                                                       ↓↓↓↓↓↓↓↓↓↓↓↓	
    _________________________________________________________________________________*/
    #[Route('/new', name: 'app_demand_new', methods: ['GET', 'POST'])]
    public function new(Request $request, DemandRepository $demandRepository, Security $security, FileUploader $fileUploader ): Response
    {
        
        $user = $security->getUser();
        $demand = new Demand();

        $form = $this->createForm(DemandType::class, $demand);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $demand->setUser($user);
            $demand->setDateCreated(new DateTime('Europe/Paris'));
            $demand->setDeleted(false);
            
            /*xxxxxxxxxxxxxxx
            x    PHOTO      x
            xxxxxxxxxxxxxxxx*/

            /** @var UploadedFile $photoFile */
            $photoFile = $form->get('photo')->getData();

            /*__________________________________________________________________________
            This condition is needed because the 'photo' field is not required
            so the photo file must be processed only when a file is uploaded         ↓ */
            if ($photoFile) {
                                
                // Updates the 'photoFilename' property to store the photo file name
                // instead of its contents
                $photoFileName = $fileUploader->upload($photoFile);

                $demand->setPhoto($photoFileName);
            }

            $demandRepository->save($demand, true);
            $demandId = $demand->getId();
            return $this->redirectToRoute('app_demand_show', ['id' => $demandId,], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('demand/new.html.twig', [
            'demand' => $demand,
            'form' => $form,
        ]);
    }
    

    /*______________________________________________________________________________

                                        SHOW
     ↓↓↓↓↓↓↓↓↓↓↓↓↓                                                       ↓↓↓↓↓↓↓↓↓↓↓↓                                   
    _________________________________________________________________________________*/
    // The parametter in the route must be 'id' so symfony will be able to get an instance from the request for "demand" 
    // Nous permet de ne pas mettre Request en paramettre et d'aller chercher la demande correspondante avec l'id :
    //$id = $request->get('id');
    //$demand = $demandRepository->findOneBy(['id'=>$id]);
    #[Route('demand/{id}', name: 'app_demand_show', methods: ['GET'])]
    public function show(Demand $demand, DemandRelationRepository $demandRelationRepository, DemandRepository $demandRepository, Security $security): Response
    {
        $user = $security->getUser();
        $demandId = $demand->getId();

        // find the Relations on this Demand instance if there is one 
        $relations = $demandRelationRepository->findBy(['demand' => $demandId,]);

        // Check if the connected user has already responded to the demand 
        $related = false;
        $relatedInfos = Null;
        foreach($relations as $relation){
            //If related user = user connected
            if($relation->getUser() == $user){
                $related = true;
                $relatedInfos = $relation;
                break;
            }
        }

        //Find the user's demand only if it is this demand instance
        //check if it is the connected user's demand
        $myDemand = $demandRepository->findOneBy(['user' => $user,'id' => $demandId,]);
 
        $mine = $myDemand ? true : false;

        if($relatedInfos){
            $replies = $relatedInfos->getMessages()->getValues();
        }
        else {
            $replies = Null;
        }
       

        return $this->render('demand/show.html.twig', [
            'demand' => $demand,
            'relations' => $relations,
            'related' => $related,
            'mine' => $mine,
            'replies' => $replies,
        ]);
    }


    /*______________________________________________________________________________

                                        EDIT
     ↓↓↓↓↓↓↓↓↓↓↓↓↓                                                       ↓↓↓↓↓↓↓↓↓↓↓↓	
    _________________________________________________________________________________*/
    #[Route('demand/{id}/edit', name: 'app_demand_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Demand $demand, Filesystem $filesystem, FileUploader $fileUploader, EntityManagerInterface $entityManager, Security $security ): Response
    {
        // Get user who posted the demand ( GET method )
        $demandUser = $demand->getUser();

        // Get user connected
        $user = $security->getUser();

        // Verify if the user who posted the demand is the one connected
        if ($demandUser == $user) {
            $form = $this->createForm(DemandType::class, $demand);
            $form->handleRequest($request);
            
            // If the form is submitted and valid, edit demand;
            if ($form->isSubmitted() && $form->isValid()) {
                $demand->setDateModified(new DateTime('Europe/Paris'));

                /*xxxxxxxxxxxxxxx
                x    PHOTO      x
                xxxxxxxxxxxxxxxx*/

                /** @var UploadedFile $photoFile */
                $photoFile = $form->get('photo')->getData();

                /*__________________________________________________________________________
                This condition is needed because the 'photo' field is not required
                so the photo file must be processed only when a file is uploaded         ↓ */
                if ($photoFile) {
                    // Get the route and the filename to delete
                    $photo = $demand->getPhoto();
                    $TargetDirectory = $fileUploader->getTargetDirectory();
                    $photo_pointer = $TargetDirectory.'/'.$photo;

                    // If the demand already has a photo, Delete the photo to be replaced, like unlink($photo_pointer);
                    if ($photo) {
                        $filesystem->remove($photo_pointer);
                    }

                    // To avoid logic in controllers, making them big, I extracted the upload logic to a separate service ( fileUploader ).
                    // Store the photo and return a new uniq name.
                    $photoFileName = $fileUploader->upload($photoFile);

                    // Store the photo file name instead of its contents
                    $demand->setPhoto($photoFileName);
                }

                $entityManager->persist($demand);
                $entityManager->flush();
               
                $demandId = $demand->getId();
                return $this->redirectToRoute('app_demand_show', ['id' => $demandId,], Response::HTTP_SEE_OTHER);
            }

            return $this->renderForm('demand/edit.html.twig', [
                'demand' => $demand,
                'form' => $form,
            ]);
        }
        else{
            return $this->redirectToRoute('app_demand_index', [], Response::HTTP_SEE_OTHER);
        }
    }


    /*______________________________________________________________________________

templates/demand/_delete_form.html.twig
<form method="post" action="{{ path('app_demand_delete', {'id': demand.id}) }}" onsubmit="return confirm('Supprimer l\'annonce : {{ demand.title}} ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ demand.id) }}">
    <button class="btn btn-danger mt-3 mb-3">Delete</button>
</form>

templates/demand/_form.html.twig
{# {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}
 #}

{{ form_start(form) }}
    {{ form_errors(form) }}

    {{ form_row(form.title) }}
    {{ form_row(form.text) }}
    <img class="card-img-top " style="width: 200px"src="{{ asset('photos/' ~ demand.photo) }}" alt="">
    {{ form_row(form.photo) }}

    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/demand/_form_update.html.twig
{# {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}
 #}

{{ form_start(form) }}
    {{ form_errors(form) }}

    {{ form_row(form.title) }}
    {{ form_row(form.text) }}
    <img class="card-img-top " style="width: 200px"src="{{ asset('photos/' ~ demand.photo) }}" alt="">
    {{ form_row(form.photo) }}
    <button class="btn btn-success">{{ button_label|default('Sauvegarder') }}</button>

    <button class="btn btn-danger" type="submit" formaction="{{ path('app_demand_delete', {'id': demand.id}) }}" onclick="return confirm('Supprimer l\'annonce : {{ demand.title}} ?');">Supprimer</button>
  
{{ form_end(form) }}

templates/demand/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Demand{% endblock %}

{% block body %}
<header class="pt-5 pb-5 d-flex flex-wrap flex-column">
        <h1 class="text-center p-5" >Editer ma demande</h1>     
</header>
<div class="container p-5">
    <div class="row justify-content-center">
        <div class="col-10" style="min-width: 300px; max-width: 600px;">

            {{ include('demand/_form_update.html.twig') }}

        </div>
    </div>
</div>  
{% endblock %}

templates/demand/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Demandes{% endblock %}

{% block body %}
<header class="pt-5 pb-5">
        {% if app.user %}
        {% endif %}
        <h1 class="text-center p-5" >Consultez les demandes sur ASK</h1>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-10" style="min-width: 300px; max-width: 600px;">
                    <form method="post" action="{{ path('app_demand_index') }}" class="container d-flex" >
                        <input class="form-control me-2" name="search" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-secondary border-2" type="submit">Search</button>
                    </form>
                </div>

            </div>
        </div>
</header>
{% for message in app.flashes('success') %}
    <div class="flash-notice alert alert-success">
        {{ message }}
    </div>
{% endfor %}
{% for message in app.flashes('danger') %}
    <div class="flash-notice alert alert-danger">
        {{ message }}
    </div>
{% endfor %}
<main class="p-5 test">

    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-5 ">

        {% for demand in demands %}

            {# Don't show the demand if is from the connected user and if he has deleted it #}
            {% if demand.user != app.user and demand.deleted == 0 %} 

                <div class="col ">
                    <div class="card shadow border-0">
                        <div class="card-body ">
           
                            <div class="card-img-top photo-profile mt-3 mb-3">

                            {% if  demand.getUser().photo %}
                                <img src="{{ asset('photos/' ~ demand.getUser().photo) }}" alt="">
                            {% else %}
                                <img src="{{ asset('photos/default_photo_profil.png') }}" alt="">
                            {% endif %}
                            
                            </div>
                            <span class="card-text m-0 pe-2">{{ demand.getUser().pseudo}}</span>
                            
                            {% if app.user %}
                                {% if demand.isRelated(app.user) %}
                                    <a href="{{ path('app_like_index', {'id': demand.getUser().id}) }}" class="js-like">
                                {% endif %}
                                
                                {# If the user who posted this demand has 0 like  #}
                                {% if demand.getUser().getLikeds() | length is same as(0) %}
                                    <span class=" m-0 js-likes-length"></span>
                                {% else %}
                                    <span class=" m-0 js-likes-length">{{ demand.getUser().getLikeds() | length}}</span>
                                {% endif %}
                        
                                    {% if demand.getUser().isLikedByUser(app.user) %}                           
                                        <i class="fa-solid fa-thumbs-up"></i>
                                    {% else %}
                                        <i class="fa-regular fa-thumbs-up"></i>
                                    {% endif %}

                                {% if demand.isRelated(app.user) %}    
                                </a>
                                {% endif %}
                            
                            {% elseif not app.user %}

                                {% if demand.getUser().getLikeds() | length is same as(0) %}
                                    <span class=" m-0 js-likes-length"></span>
                                {% else %}
                                    <span class=" m-0 js-likes-length">{{ demand.getUser().getLikeds() | length}}</span>
                                {% endif %}
                                <i class="fa-regular fa-thumbs-up"></i>
                                
                            {% endif %}

                            <h5 class="card-title m-0 overflow-hidden" style="height: 24px;">{{ demand.title }}</h5>
                            <small class="text-muted"> {{ demand.getUser().location }}</small>
                            <p class="card-text mt-3 mb-3 overflow-hidden" style="height: 100px;">{{ demand.text }}</p>
                        </div>
                        <div class="card-footer d-flex flex-wrap justify-content-between ">
                        <a class="btn btn-primary  mt-3 mb-3" href="{{ path('app_demand_show', {'id': demand.id}) }}">Consulter</a>
                        {% if demand.dateModified %}
            
                            <small class="text-muted align-self-end">Modifié le {{ demand.dateModified ? demand.dateModified|date('d-m-Y') : '' }}</small>
                        {% else %}
            
                            <small class="text-muted align-self-end">Créé le {{ demand.dateCreated ? demand.dateCreated|date('d-m-Y') : '' }}</small>
                        {% endif %}
            
                        </div>
                    </div>   
                </div>              
            {% endif %}
        {% else %}
      
            <span>Aucun résultat</span>
                
        {% endfor %}
    </div>

</main>   
{% endblock %}

templates/demand/my_demands.html.twig
{% extends 'base.html.twig' %}



{% block title %}Mes demandes{% endblock %}

{% block body %}
<header class="pt-5 pb-5 d-flex flex-wrap flex-column">
        <h1 class="text-center p-5" >Mes demandes</h1>     
</header>

<div class="p-5">

    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-5 ">

        {% for demand in demands %}

            {# Don't show the demand if is from the connected user and if he has deleted it #}
            {% if demand.deleted == 0 %} 

                <div class="col">
                    <div class="card shadow border-0">
                        <div class="card-body ">
                            <div class="card-img-top photo-profile mt-3 mb-3">

                                {% if  demand.getUser().photo %}
                                    <img src="{{ asset('photos/' ~ demand.getUser().photo) }}" alt="">
                                {% else %}
                                    <img src="{{ asset('photos/default_photo_profil.png') }}" alt="">
                                {% endif %}
                    
                                {# <img class="card-img-top w-25 rounded-circle mt-3 mb-3" src="{{ demand.getUser().photo }}" alt=""> #}   
                            
                            </div>
                            {# <img class="card-img-top w-25 rounded-circle mt-3 mb-3"style="max-width: 100px" src="{{ demand.getUser().photo }}" alt=""> #}
                            <span class="card-text">{{ demand.getUser().pseudo }}</span>
                            <h5 class="card-title m-0">{{ demand.title }}</h5>
                            <small class="text-muted"> {{ demand.getUser().location }}</small>
                            <p class="card-text mt-3 mb-3 overflow-hidden" style="height: 100px;">{{ demand.text }}</p>
                        </div>
                        <div class="card-footer d-flex flex-wrap justify-content-between ">
                       
                    

                                <div class="row">
                                    <div class="col">
                                        <a class="btn btn-primary mt-3 mb-3" href="{{ path('app_demand_show', {'id': demand.id}) }}">Consulter</a>
                                    </div>
                                    <div class="col">
                                        <a class="btn btn-secondary mt-3 mb-3" href="{{ path('app_demand_edit', {'id': demand.id}) }}">edit</a>
                                    </div>
                                    <div class="col">
                                        {{ include('demand/_delete_form.html.twig', {'id': demand.id}) }}
                                    </div>
                                </div>

                        
                        {% if demand.dateModified %}
            
                            <small class="text-muted align-self-end">Modifié le {{ demand.dateModified ? demand.dateModified|date('d-m-Y') : '' }}</small>
                        {% else %}
            
                            <small class="text-muted align-self-end">Créé le {{ demand.dateCreated ? demand.dateCreated|date('d-m-Y') : '' }}</small>
                        {% endif %}
            
                        </div>
                    </div>   
                </div>              
            {% endif %}
        {% else %}
      
            <span>Aucun résultat</span>
                
        {% endfor %}
    </div>
</div>
    

{% endblock %}

templates/demand/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Demand{% endblock %}

{% block body %}
    <header class="pt-5 pb-5 d-flex flex-wrap flex-column">
            <h1 class="text-center pt-5 pb-5">Créez votre demande</h1>    
    </header>
    <div class="container p-5">
        <div class="row justify-content-center">
            <div class="col-10" style="min-width: 300px; max-width: 600px;">

                {{ include('demand/_form.html.twig') }}

            </div>
        </div>
    </div>    
{% endblock %}